# Generated by Django 3.1.4 on 2020-12-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user_id',
            new_name='user',
        ),
    ]
